version: '3.1'

services:
  wp-db:
    build:
      context: ../
      dockerfile: deployment/mysql.Dockerfile
    restart: always          
    hostname: mysql
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=mojtaba6128
      - MYSQL_ROOT_PASSWORD=mojtaba6128
    ports:
      - 33070:3306
    networks:
      wp-net:
        ipv4_address: 172.30.10.10
        aliases :
          - wdb

  wp-app:
    image : wordpress:latest
    restart: always      
    volumes:
      - wp-data:/var/www/html/
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_HOST=wdb:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=mojtaba6128
    hostname : wordpress
    depends_on:
        - wp-db     
    networks:
      wp-net:
        ipv4_address: 172.30.10.20
 
  wp-web:
    build:
      context: ../
      dockerfile: deployment/nginx.Dockerfile
    restart: always         
    working_dir: /var/www
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mojtaba/wordperss-app/nginx/conf.d:/etc/nginx/conf.d 
      - /mojtaba/wordperss-app/nginx/cert:/etc/nginx/cert
    links:
        - wp-app       
    networks:
      wp-net:
        ipv4_address: 172.30.10.30

volumes:
  wp-data:
  db-data:
  
networks:
  wp-net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.30.10.0/24   
     

